# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\mainWindow2.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(760, 300)
        MainWindow.setMinimumSize(QtCore.QSize(760, 300))
        MainWindow.setMaximumSize(QtCore.QSize(760, 300))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(430, 0, 437, 271))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.formLayout_2 = QtWidgets.QFormLayout()
        self.formLayout_2.setObjectName("formLayout_2")
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label.setObjectName("label")
        self.formLayout_2.setWidget(
            0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.loginBiliBtn = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.loginBiliBtn.setMaximumSize(QtCore.QSize(200, 16777215))
        self.loginBiliBtn.setObjectName("loginBiliBtn")
        self.formLayout_2.setWidget(
            0, QtWidgets.QFormLayout.FieldRole, self.loginBiliBtn)
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.formLayout_2.setWidget(
            1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.clipCheck = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.clipCheck.setObjectName("clipCheck")
        self.formLayout_2.setWidget(
            1, QtWidgets.QFormLayout.FieldRole, self.clipCheck)
        self.label_4 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.formLayout_2.setWidget(
            2, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.autoCloseCheck = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.autoCloseCheck.setObjectName("autoCloseCheck")
        self.formLayout_2.setWidget(
            2, QtWidgets.QFormLayout.FieldRole, self.autoCloseCheck)
        self.autoClipLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.autoClipLabel.setObjectName("autoClipLabel")
        self.formLayout_2.setWidget(
            3, QtWidgets.QFormLayout.LabelRole, self.autoClipLabel)
        self.autoClipCheck = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.autoClipCheck.setObjectName("autoClipCheck")
        self.formLayout_2.setWidget(
            3, QtWidgets.QFormLayout.FieldRole, self.autoClipCheck)
        self.label_3 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.formLayout_2.setWidget(
            4, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.verticalLayout.addLayout(self.formLayout_2)
        self.logText = QtWidgets.QTextBrowser(self.centralwidget)
        self.logText.setGeometry(QtCore.QRect(0, 0, 431, 280))
        self.logText.setObjectName("logText")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(430, 130, 305, 105))
        self.label_5.setObjectName("label_5")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 760, 33))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.retranslateUi(MainWindow)
        self.loginBiliBtn.clicked.connect(MainWindow.login)  # type: ignore
        self.clipCheck.clicked['bool'].connect(
            MainWindow.qrCodeSwitch)  # type: ignore
        self.autoCloseCheck.clicked['bool'].connect(
            MainWindow.autoCloseSwitch)  # type: ignore
        self.autoClipCheck.clicked['bool'].connect(
            MainWindow.autoClipSwitch)  # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "崩坏3外置扫码器 v.1.4.9"))
        self.label.setText(_translate("MainWindow", "登录B站账户"))
        self.loginBiliBtn.setText(_translate("MainWindow", "点击登录"))
        self.label_2.setText(_translate(
            "MainWindow", "<html><head/><body><p>解析二维码</p></body></html>"))
        self.clipCheck.setText(_translate("MainWindow", "当前状态:关闭"))
        self.label_4.setText(_translate("MainWindow", "扫码完成后自动退出"))
        self.autoCloseCheck.setText(_translate("MainWindow", "当前状态:关闭"))
        self.autoClipLabel.setText(_translate("MainWindow", "自动尝试截屏"))
        self.autoClipCheck.setText(_translate("MainWindow", "当前状态:关闭"))
        self.label_3.setText(_translate("MainWindow", "Powered By Hao_cen"))
        self.logText.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
                                        "<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
                                        "p, li { white-space: pre-wrap; }\n"
                                        "hr { height: 1px; border-width: 0; }\n"
                                        "li.unchecked::marker { content: \"\\2610\"; }\n"
                                        "li.checked::marker { content: \"\\2612\"; }\n"
                                        "</style></head><body style=\" font-size:9pt; font-weight:400; font-style:normal;\">\n"
                                        "<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'SimSun\';\"><br /></p></body></html>"))
        self.label_5.setText(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
                                        "<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
                                        "p, li { white-space: pre-wrap; }\n"
                                        "hr { height: 1px; border-width: 0; }\n"
                                        "li.unchecked::marker { content: \"\\2610\"; }\n"
                                        "li.checked::marker { content: \"\\2612\"; }\n"
                                        "</style></head><body style=\" font-size:9pt; font-weight:400; font-style:normal;\">\n"
                                        "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">简易使用说明：</p>\n"
                                        "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">第一次使用需要点击登录按钮登录B站账号</p>\n"
                                        "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">后续会将账号密码储存在配置文件内</p>\n"
                                        "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">自动登录解析二维码启用时 读取剪贴板内二维码</p>\n"
                                        "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">如果为 崩坏3登陆二维码 则执行扫码</p>\n"
                                        "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">自动尝试截屏仅在 崩坏3 为焦点</p><p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">且 自动退出启用 时可用</p></body></html>"))
